### ISSUE TITLE
Invalid CMP (Setono Sylius) detected

### ISSUE THREAD

**Issue by j4k0xb** [cavi-au/Consent-O-Matic#104]
the console logs this on every site I visit:
```
Invalid CMP (Setono Sylius) detected, please update GDPR consent engine or fix the rule generating this error:
ConsentEngine.js:21 TypeError: Cannot read properties of undefined (reading 'type')
    at Matcher.createMatcher (Matcher.js:3:23)
    at Detector.js:19:47
    at Array.forEach (<anonymous>)
    at new Detector (Detector.js:18:36)
    at CMP.js:9:33
    at Array.forEach (<anonymous>)
    at new CMP (CMP.js:8:26)
    at ConsentEngine.js:18:32
    at Array.forEach (<anonymous>)
    at new ConsentEngine (ConsentEngine.js:16:29)
```

seems to be because it has no showingMatcher

**Comment by dkgof** [comment]
The latest code, not yet released, no longer requires a showing matcher, and i forgot that i was running the dev build when creating that rule. I fixed it so its compatible with the old release. Thanks for the report.
