### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'trim')

### ISSUE THREAD

**Issue by benyaa** [cavi-au/Consent-O-Matic#471]
So, I was trying to enter `https://www.orange.fr/portail` when I noticed that the extension doesn't go over all of the settings and because of this the consent popup won't let it submit. 
I tried adding the 2 additional actions to `didomi.io` rule:
```json
{
                                        "type": "ifcss",
                                        "target": {
                                            "selector": ".didomi-components-accordion",
                                            "textFilter": [
                                                "Expérience enrichie"
                                            ]
                                        },
                                        "trueAction": {
                                            "type": "consent",
                                            "consents": [
                                                {
                                                    "trueAction": {
                                                        "type": "click",
                                                        "target": {
                                                            "selector": ".didomi-consent-popup-data-processing__buttons .didomi-components-radio__option:nth-child(2)"
                                                        }
                                                    },
                                                    "falseAction": {
                                                        "type": "click",
                                                        "target": {
                                                            "selector": ".didomi-consent-popup-data-processing__buttons .didomi-components-radio__option:nth-child(1)"
                                                        }
                                                    },
                                                    "type": "X"
                                                }
                                            ]
                                        }
                                    },
                                    {
                                        "type": "ifcss",
                                        "target": {
                                            "selector": ".didomi-components-accordion",
                                            "textFilter": [
                                                "Publicité ciblée"
                                            ]
                                        },
                                        "trueAction": {
                                            "type": "consent",
                                            "consents": [
                                                {
                                                    "trueAction": {
                                                        "type": "click",
                                                        "target": {
                                                            "selector": ".didomi-consent-popup-data-processing__buttons .didomi-components-radio__option:nth-child(2)"
                                                        }
                                                    },
                                                    "falseAction": {
                                                        "type": "click",
                                                        "target": {
                                                            "selector": ".didomi-consent-popup-data-processing__buttons .didomi-components-radio__option:nth-child(1)"
                                                        }
                                                    },
                                                    "type": "X"
                                                }
                                            ]
                                        }
                                    },
```

but now, instead of saving it, it fails with:
```
Error during consent handling: TypeError: Cannot read properties of undefined (reading 'trim')
    at t.findElement (content.js:1:4824)
    at t.find (content.js:1:7054)
    at f.execute (content.js:1:15919)
    at u.execute (content.js:1:13953)
    at async y.execute (content.js:1:17347)
    at async u.execute (content.js:1:13945)
    at async A.runMethod (content.js:1:24650)
    at async content.js:1:29697
```
spec:
* Chrome Version 127.0.6533.99 (Official Build) (64-bit)
* Ubuntu Cinnamon 24.04
* Consent-O-Matic 1.1.0

Thanks

**Comment by benyaa** [comment]
Ok, so the fix in for this is to change:
`if(options.selector.trim() === ":scope")` to `if(options.selector === undefined || options.selector.trim() === ":scope")` in `Tools.js`.
